### ISSUE TITLE
Problem: The device cannot be switched to Operate

### ISSUE THREAD

**Issue by jiang-qihang** [unref-ptr/lwIOLink#3]
I try to use max22513 as Phy of io-link

But when switching to the state of operate, it got stuck

I use the evaluation board of i-link protocol and MAXREF145 evaluation board to communicate with IO-Link slaves respectively.

After I checked, the device successfully entered the run mode, and successfully parsed to the first frame 0xA2 and CKT. After completing the following analysis, enter rsp
However, the command to switch the state has not been received, and the device is always in the run mode state without jumping out.

my question:
1. What might be the reason why the device is not switched to operate?
2. Does the protocol stack of the iolink master switch the device state in other ways?

My environment:
Arduino Mega 2560 + MAX22513 Evaluation Kit

Note 1: Due to the limited external interrupt pins of 2560, changed the Wake-up pin to Pin = 2
Note 2: The 2560 reads and writes the registers of the 22513 through the I2C protocol to enable

Excuse my broken English,
And to express my thanks for this IwLOlink library

**Comment by unref-ptr** [comment]
> What might be the reason why the device is not switched to operate?

My guess is that something else due to your hardware (ATmega2560 or MAX22513) could be the issue. 

> Does the protocol stack of the iolink master switch the device state in other ways?

To change the state the IO-Link Master sends a master command, please refer to Table B.2 of the specification (v1.1.2)

If you have a logic analyzer you can capture TX,RX, and Wakeup pin to try to debug the communication.

**Comment by jiang-qihang** [comment]
thank you for your reply,
I have already solved part of the previous problem
I used an oscilloscope to check the mega2560 and max22513, and the serial data can be sent and received normally. There may be no problem with the hardware.
I have checked that the slave is receiving the correct wakeup sequence and the corresponding command


**Problem 1** (partially resolved): Unable to switch to preop and op mode
**Reason: I** put too many printfs for checking, making the program slow

After deleting the printf check, the program can switch to the pre-op state under the communication of the master station, but the master station program reports an error, indicating that some responses from ISDU are needed
Errors like:

-   iolink dl isdu h sm isdu wait3: ISDUWait. No service!
- (ERROR] AL: ISDU read cnf: Got unexpected qualifier 0x06

**Now the problem seems to be related to ISDU, which is currently an undeveloped feature. It seems that the IO-Link communication cannot enter the periodic communication mode.
If I just want to transfer 1-3 bytes of process data (PDin) to the master, no other complex functions involved, is this possible?**

**Can the slave station without ISDU function communicate with the master station normally?**

**Comment by unref-ptr** [comment]
About your first problem, as mentioned in the readme the library works in polling mode (due to Arduino´s limited API). For this reason you should not call any blocking functions in the loop as it can interfer with the IO-Link communication deadlines (see Figure A.15 symbol TA spec v1.1.3).

Is your scope capable of decoding Serial communication ? That would help to check the complete communication, if not you can plug a logic analyzer in the TTL logic level pins of the Arduino (TX,RX).

This library bypasses ISDU by indicating that ISDU is not supported in the MSEQ capability parameter (see spec Annex B.1.4)

https://github.com/unref-ptr/lwIOLink/blob/21edf6bff36d3e5c637e4e33988dead5287eb6fa/src/lwIOLink.hpp#L218
https://github.com/unref-ptr/lwIOLink/blob/21edf6bff36d3e5c637e4e33988dead5287eb6fa/src/lwIOLink.cpp#L156

**Comment by unref-ptr** [comment]
You also have to be sure that the port which is connected on the IO-Link master has Identification checked disabled. 

See Table E.3 – PortConfigList (spec v1.1.3) , element name `Validation&Backup`. 

This is manufacturer specific so please check your IO-Link Master instruction manual on how to disable port check.

**Comment by unref-ptr** [comment]
Will close the issue, feel free to open it if you have any updates.
